version: "3.8"

services:
    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb
        container_name: mariadb
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        env_file:
            - .env
    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        depends_on:
            - mariadb
        image: wordpress
        container_name: wordpress
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        env_file:
            - .env
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        depends_on:
            - wordpress
        image: nginx
        container_name: nginx
        volumes:
            - wordpress:/var/www/html
        ports:
            - "443:443"
        networks:
            - inception
        env_file:
            - .env

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: '/home/ekenane/data/vol-wpf'
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: '/home/ekenane/data/vol-wpdb'
      o: bind

networks:
  inception:
    driver: bridge