# The version property is now purely informative. Docker Compose does not rely on this property to determine how to process the Compose file.
# When you use the version property, Docker Compose will issue a warning indicating that it is obsolete and should not be used in new Compose files.
# version: "3.8"
name: inceptionProject

services:
    db-service:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        container_name: db
        # volumes:
        #     - /Users/ekenane/Desktop/volumeWpDatabase:/var/lib/mysql/mariadb
        networks:
            - inc
    wp-service:
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        depends_on:
            - db-service
        container_name: wp
        ports:
            - "9000:9000"
        volumes:
            - /Users/ekenane/Desktop/vol:/var/www/html
        networks:
            - inc
    nginx-service:
    # If a -service definition in your docker-compose.yml file uses the build attribute but does not specify an image attribute (i.e., it does not provide the name of an existing image from a registry), Docker Compose will not attempt to push the built image to a registry automatically.
    # Instead, Docker Compose will warn you about the missing image attribute. This warning serves as a reminder that the built image will not be pushed to a registry unless you explicitly specify where it should be pushed.
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        depends_on:
            - wp-service
        container_name: nginx
        volumes:
            - /Users/ekenane/Desktop/vol:/var/www/html
        ports:
            - "443:443"
        networks:
            - inc

networks:
    inc: